### ISSUE TITLE
filter by borrowing event date

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/geotaste#17]
- [ ] Design filter component
- [ ] Write tests to validate output

Questions:
  - do we use start date, end date, or calculate duration?
  - account for books with missing date
  - limit to year?

**Comment by quadrismegistus** [comment]
* We ended up using the year for start_date on the events
* But we'll experiment with adding a month slider (1 ... 12)

**Comment by quadrismegistus** [comment]
Done
