### ISSUE TITLE
Individual members on map

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/geotaste#29]
When I select individual members, the map doesn't regenerate to show only their addresses.

<img width="1639" alt="Screenshot 2023-06-24 at 2 31 14 PM" src="https://github.com/Princeton-CDH/geotaste/assets/12616674/7f5be8e9-6c9d-48d5-aca0-97c1f0d8f9c5">

**Comment by quadrismegistus** [comment]
Thanks Josh. 

Note to self: this is working now but clicking the blue "X" on a person's name does not remove them from the filter -- @TODO

**Comment by quadrismegistus** [comment]
Eh—this seems ok to me as is. We can reopen this if necessary but it's not very different from how other filters work
