### ISSUE TITLE
August MVP

### ISSUE THREAD

**Issue by quadrismegistus** [Princeton-CDH/geotaste#58]
# GeoTaste August MVP

## General Design Improvements

- [x] #59
- [x] #60
- [x] #70
- [x] #71
- [x] #72
- [x] Closer zoom on S&C landmark on first open
- [x] Make filters smaller – change to 20% or 18% width
- [x] #61
- [x] #62
- [x] #63
- [x] #64
- [x] Relabel filters: “Filter 1” and “Filter 2”
- [x] Redo title, delete compass: Shakespeare and Company Project Lab, use head to link to main site. Match font: Louiza [JK can provide]
- [x] #73
- [x] Make faster? 
- [x] #65
- [x] #74
- [x] #75
- [x] #76

## Analysis + Tooltips Improvements

- [x] Make analysis tab a summary of landmarks/stat overview when no data selected, then a summary of selected data when 1 or more filters is applied
- [x] [-] should be [+] 
- [x] “Summary” sentence on each level (no selection). No selection should have a how-to guide or message
- [x] #66
- [x] Do we want the points to be proportional to borrows? Seems like no – all points the same size – so pick one size and stick to it
- [x] I have to think about the filter labels and explanations—but what we have now is good and will hold us!

## Data Tab Improvements

- [x] #67
- [x] #68
- [x] #69

**Comment by jkotin** [comment]
Adding some MVP points from the data research side -- these are necessary for the 1.3 dataset release:

- [ ] finish census survey -- we only have 5, 7, and 16 left to complete, ETA 8/31
- [ ] go through members with multiple addresses
- [ ] check and supplement author nationality and gender

**Comment by quadrismegistus** [comment]
I think we're now done with this!
